# Pytorch Tensor

#### 0. Import Library

In [2]:
import torch
import numpy as np

/home/ibo703/anaconda3/envs/Study/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


#### 1. Tensor
- Tensor : Pytorch에서 사용하는 자료구조로서 배열, 행렬과 유사하다.

#### 2. How to generate a Tensor

In [10]:
# 1. 직접 데이터로부터 Tensor 생성하기
data = [[1, 2], [3, 4], [5, 6]]
t_from_data = torch.tensor(data)
print(t_from_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [12]:
# 2. Numpy로부터 Tensor 생성하기
np_array1 = np.array(data)
t_from_np = torch.from_numpy(np_array1)
print(t_from_np)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [16]:
# 3. 다른 Tensor로부터 생성하기 --> 다른 텐서처럼 생성하기
t_from_t = torch.ones_like(t_from_np)
print(t_from_t)
t_from_t = torch.zeros_like(t_from_np)
print(t_from_t)

tensor([[1, 1],
        [1, 1],
        [1, 1]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])


In [30]:
# 4. 랜덤 or 상수 값 사용해 생성하기
shape = [4, 4]

t_from_rand = torch.rand(shape)
print(f"Random Tensor :\n{t_from_rand} \n")

t_from_ones = torch.ones(shape)
print(f"Ones Tensor :\n{t_from_ones} \n")

t_from_zeros = torch.zeros(shape)
print(f"Zeros Tensor : \n{t_from_zeros} \n")

Random Tensor :
tensor([[0.5465, 0.2265, 0.3148, 0.6034],
        [0.9433, 0.7936, 0.7755, 0.9546],
        [0.0693, 0.6017, 0.6095, 0.5373],
        [0.1426, 0.9145, 0.5400, 0.5442]]) 

Ones Tensor :
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor : 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



#### 3. Tensor's Attribute

In [32]:
# Tensor's Attribute
np_array2 = np.array([[1, 2], [3, 4]])
t2_from_np = torch.from_numpy(np_array2)

print(f"tensor.shape = {t2_from_np.shape}") # shape
print(f"tensor.dtype = {t2_from_np.dtype}") # data type
print(f"tensor.device = {t2_from_np.device}") # device(cpu or cuda)

tensor.shape = torch.Size([2, 2])
tensor.dtype = torch.int64
tensor.device = cpu


#### 4. Tensor Operation

In [53]:
# 0. CUDA SETTING
tensor = torch.ones([4, 4])
if torch.cuda.is_available():
    t = tensor.to('cuda:2')
else:
    t = tensor.to('cpu')

print(f"t.device = {t.device}")
print(f"tensor : \n{t}")

t.device = cuda:2
tensor : 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:2')


In [54]:
# 1. Indexing & Slicing
t[:, 2] = 0 
print(t)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]], device='cuda:2')


In [55]:
# 2. Concatenate
t1 = torch.cat([t, t], dim=1)
t1

tensor([[1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1.]], device='cuda:2')

In [62]:
# 3. Multipy

# element-wise product
t2 = t * t
print(t2)
t2 = t.mul(t)
print(t2)


# matrix multiplication
t3 = t @ t
print(t3)

t3 = t.matmul(t)
print(t3)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]], device='cuda:2')
tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]], device='cuda:2')
tensor([[3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [3., 3., 0., 3.]], device='cuda:2')
tensor([[3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [3., 3., 0., 3.]], device='cuda:2')


In [63]:
# 4. In-place
t4 = t.add_(5)
print(t4)

tensor([[6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.]], device='cuda:2')


#### 5. Numpy Bridge

In [68]:
tensor = torch.ones(5)

np_array = tensor.numpy() # CPU여야 가능?
print(np_array)

tensor2 = torch.from_numpy(np_array)
print(tensor2)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])
